export default {
  START_SCRIPT: Symbol.for("START_SCRIPT"),
  MIGRATION_SCRIPT: Symbol.for("MIGRATION_SCRIPT"),
  MODULE_REGISTRY: Symbol.for("MODULE_REGISTRY"),
  MODULE_FACTORY: Symbol.for("MODULE_FACTORY"),
  MODULE_REPOSITORY: Symbol.for("MODULE_REPOSITORY"),
  DB_DATA_REPOSITORY: Symbol.for("DB_DATA_REPOSITORY"),
  ENTITY_MANAGER: Symbol.for("ENTITY_MANAGER"),
  EVENT_OBSERVER: Symbol.for("EVENT_OBSERVER"),
};
