export enum ERRORS {
  UNKNOWN = "UNKNOWN",
  PERMISSION_DENIED = "PERMISSION_DENIED",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  DUPLICATE_ENTRY = "DUPLICATE_ENTRY",
  NO_SUCH_ENTITY = "NO_SUCH_ENTITY",
}

export const HTTP_CODES = {
  UNKNOWN: 500,
  PERMISSION_DENIED: 404,
  VALIDATION_FAILED: 403,
  DUPLICATE_ENTRY: 500,
  NO_SUCH_ENTITY: 404,
} as { [key: string]: number };
