export default {
  BOT_RUN_SCRIPT: Symbol.for("BOT_RUN_SCRIPT"),
  USER_REPOSITORY: Symbol.for("USER_REPOSITORY"),
  NOTE_REPOSITORY: Symbol.for("NOTE_REPOSITORY"),
  TELEGRAM_BOT: Symbol.for("TELEGRAM_BOT"),
  TEXT_STRATEGY_FACTORY: Symbol.for("TEXT_STRATEGY_FACTORY"),
  CALLBACK_STRATEGY_FACTORY: Symbol.for("CALLBACK_STRATEGY_FACTORY"),
};
